### ISSUE TITLE
Obsidian Version Mismatch

### ISSUE THREAD

**Issue by thecookiemomma** [Gorkycreator/obsidian-quick-tagger#3]
As I stated on the Forums, I attempted to use BRAT to install your plugin.  

### Expected result: 
Install the plugin, see if it works. 

### Achieved result: 
an error message from BRAT saying, "Your plugin says that Obsidian must be version 1.16.  Please update your Obsidian and try again."  I imagine this is an oversight either here or elsewhere... I wanted to point it out so that you can get this lovely plugin off the ground.  Can't wait! 

Thank you for your hard work. Can't wait to see what happens.

**Comment by Gorkycreator** [comment]
Thanks for checking out the plugin and providing feedback!

This was indeed a typo. Looking into how BRAT works revealed the git tags were also formatted incorrectly. I've patched these problems and was able to get it installed with BRAT after the fixes. Please feel free to give it another go and let me know if you hit any further snags.

**Comment by thecookiemomma** [comment]
That absolutely worked. Thank you.  Looking forward to using this especially in conjunction with Obsidian's new "Importer" plugin to bring in my old EN notes.
