### ISSUE TITLE
does not always seem to work with multiple tags. 

### ISSUE THREAD

**Issue by pictoys** [Gorkycreator/obsidian-quick-tagger#4]
it seems to fail to tag to tag on multiple files with multiple tags and only tag the first one

**Comment by Gorkycreator** [comment]
Thanks for bringing this to my attention. The plugin automatically reduces the number of notes after a tag is selected if the selected notes already have the tag on them. Thereby, if you select five notes and four of them are already tagged with `#mySelectedTag`, only the note lacking `#mySelectedTag` will be changed.

If you're experiencing this in a different scenario, please let me know more precise steps I can take to repeat this issue and I'll do my best to troubleshoot what's going wrong.

**Comment by pictoys** [comment]
Hi Gorky, thanks for getting back.
It seems to fail to do so. sometimes i get the tag on all notes, sometimes only on the first one. would it recognize a tag like tags: [tagA, tagB]?

**Comment by Gorkycreator** [comment]
Yes, it will recognize all frontmatter tags that Obsidian considers valid:

```
tag: [tag1, tag2]
```

```
tags: tag1 tag2
```

```
Tags: tag1, tag2
```

```
Tag:
  - tag1
  - tag2
```

Note that the quick-tagger plugin consolidates these all into a single `tags` list. The plugin should solve this, not cause it, but if your note has a combination of `tag`, `tags`, `Tag`, and `Tags` in the frontmatter, only one will show in reading mode.

Please keep searching for a way to repeat the error you're seeing. Once you have a way to consistently repeat the bug, let me know and I can dig into it and identify the cause.

**Comment by pictoys** [comment]
I just realized the side panel buttins are only for single tagging. right click menue works fine, lol.

**Comment by Gorkycreator** [comment]
Aha, thanks for the update! I see how that could be confusing.

I'll see if there are any improvements I can make with the ribbon icons, either by clarifying they only act on the current note or making it work with multiple notes selected. Unfortunately, I'm under the impression that the latter option will be too tricky and fragile.
